---
title: "lab manual"
page-layout: full
---

<script>
  // Prompt for password when the page is loaded
  document.addEventListener("DOMContentLoaded", function () {
    const correctPassword = "howard1867"; // Replace with your desired password
    let userPassword = prompt("Please enter the password to access this page:");

    if (userPassword !== correctPassword) {
      alert("Incorrect password! You will be redirected.");
      window.location.href = "/"; // Redirect to another page (e.g., homepage)
    }
  });
</script>

This area is for lab members only.

#### Welcome members!

We are excited to have you join the Quantitative Histories Workshop! This section contains links to the required on-boarding documents that you will need to complete for our lab. When completing documents with sensitive information, please do not upload or email personal details (such as your SSN). Instead, you should stop by a Faculty Director's office hours to finalize any forms. 

For your first task, please complete the following steps below:

| <u>Step 1: Contact information </u>

- To complete the *Quantitative Histories Workshop Information Form*, please click [here](https://forms.gle/FS2RgyaTWZNGyHr89).

| <u>Step 2: Paperwork </u>

- Please speak with a lab director.

| <u>Step 3: Project on-boarding </u>

- Members must complete on-boarding for their project group; please see your group leader. 

- Generally, all members new to coding for our lab should start here:

## Lessons

::: column-inset
| Lesson |       Title       | Resources |
|:------:|:------|--------|
| [0](lessons/lesson00.html) | [Getting started](lessons/lesson00-slides.html) | |
| [1](lessons/lesson01.html) |[Introduction to the Quantitative Histories Workshop Model](lessons/lesson01-slides.html) |  |
| [2](lessons/lesson02.html) |[Case Study 1: Fatal Police Interactions](lessons/lesson02-slides.html) |  |
| [3](lessons/lesson03.html) |[Case Study 2: The Red Record](lessons/lesson03-slides.html) |  |

:::
