---
title: "People and Partners"
---

Our lab is made up of a highly versatile and collaborative team of researchers. 

# People

<u>Current Lab Members</u>

- Amir Harris (Morehouse College)
- Basil Ghali (Howard University, PhD student; Morehouse College, Class of 2023)
- Benjamin Holman (Morehouse College)
- Gabriella Walker (Spelman College)
- Jalil Cooper (Stanford University)
- Jana Turner (Howard University)
- Jeremiah Lowther (Morehouse College)
- Julian Amaya (Morehouse College)
- Kade Davis (Morehouse College)
- Kenthia Roberts (Columbia University, MS student; Howard University, Class of 2023)
- Kyshan Nicols-Smith (Morehouse College)
- Myles Ndiritu (Morehouse College)
- Sayid Achilov (Dartmouth High)

# Partners

## Collaborators

### Project collaborators

Hye Ryeon Jang, Morehouse College

Harlin Lee, University of North Carolina at Chapel Hill

Joseph Dixon, Independent Consultant

Lorenzo Harper, University of North Carolina at Charlotte

### Program collaborators

The Carpentries

Data Science Academy at NC State

Data Science Institute (DSI) at the University of Chicago

US-Africa Institute

### Funders

Alfred P. Sloan Foundation

Atlanta University Center Data Science Initiative (AUC DSI)

Center for Applied Data Science and Analytics (CADSA) at Howard University

Data.org

Institute for Racial Justice at Loyola University, Chicago

---

<u>Former Lab Members</u>

- Ronald Carter (Howard University, MS student)
- Maya Phillips (Spelman College, Class of 2023)
- Dalton Favors (Morehouse College, Class of 2024)
- Hasan Henry (Morehouse College, Class of 2024)
- Matthew Mann (Morehouse College, Class of 2022)
- Xavier McKenzie (Morehouse College, Class of 2023)

