---
title: "Notes from The Workshop"
page-layout: full
about:
  template: trestles
  image-width: 20em
  image-shape: round
  links:
    - icon: github
      text: Github
      href: https://github.com/quant-shop
---

- general workshops

  - [introduction to computational studies in education and the social sciences](https://quant-shop.github.io/intro-comp-educ-soc/){.external target="_blank"}
  
  - [data science for social impact in higher education](https://rpubs.com/professornaite/dssi){.external target="_blank"}
  
- demography

  - [critical computational geographies](https://rpubs.com/professornaite/crit-comp-geo-pt1){.external target="_blank"}

  - [census history project, phase 1: race and ethnicity](https://professornaite.github.io/echo/){.external target="_blank"}

  - [census history project, phase 2: multidimensionality (forthcoming)](https://rpubs.com/professornaite/dc-open-data-2025){.external target="_blank"}
  
- education

  - [racism in STEM education](https://professornaite.github.io/racism-stem-ed/){.external target="_blank"}
  
  - [black like me](https://quant-shop.github.io/black-like-me/){.external target="_blank"}
  
  - [fugitive pedagogies in STEM (forthcoming)](){.external target="_blank"}

- state violence

  - [FATAL: a study of fatal police interactions in the united states](https://github.com/quant-shop/fatalv2){.external target="_blank"}

  - [bob](https://professornaite.github.io/bob){.external target="_blank"}
  
- abolition

  - [a quantitative abolitionist inquiry, phase 1: lynching](https://quant-shop.github.io/red-record){.external target="_blank"}

  - [a quantitative abolitionist inquiry, phase 2: policing](https://quant-shop.github.io/fatal-app/){.external target="_blank"}

- the OG: Du Bois

  - [data and Du Bois](https://quant-shop.github.io/dubois-infographics){.external target="_blank"}
  
  - [the Atlanta University Studies](https://quant-shop.github.io/atlanta-university-studies){.external target="_blank"}
  
- politics and policy

  - [rock the vote (forthcoming)](/img/rock-the-vote.png){.external target="_blank"}
  
- have an idea? contact us at quantshopusers [at] gmail [dot] com

we support equitable open source practices. see a list of our repositories [here](https://github.com/quant-shop){target="_blank"}.
